import { Header } from '@/components/index'
import { Kanit, Kumbh_Sans } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const kanit = Kanit({
  weight: ['400', '500','700', '800'],
  subsets: ["latin"]
})

const kumbhSans = Kumbh_Sans({
  weight: ['400', '500','700', '800'],
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={kumbhSans.className}>
      <Header />
      <body style={{paddingTop: 70}}>{children}</body>
    </html>
  )
}
