import { Kanit } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const kanit = Kanit({
  weight: ['400', '500','700', '800'],
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={kanit.className}>
      <body>{children}</body>
    </html>
  )
}
